Add H2 database to store application data
akuniutka/java-filmorate pull request #5
Opened 2024-08-12 01:11 UTC by akuniutka

Achieve a sprint #12 goals:

- Add H2 database to store application data.
- Add film genres.
- Add MPA ratings.
- Change users 'friendship'-relations to subscription-like ones.
- Add database schema.
- Add database integration tests.

2024-08-13 07:17 UTC, YazykovMikhail requested changes

2024-08-13 07:17 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                .peek(f -> f.setGenres(genreService.getGenresByFilmId(f.getId())))
Вызывать в цикле запросы не стоит, на каждый запрос создается соединение это тяжеловестная операция. 

Сделай в GenreDbStorage метод 	public void load(List<Film> films) {
и вызывай тут его для подгрузки данных для Фильмов, из FilmServiceImpl можно вызывать сразу GenreDbStorage
Метод будет выглядеть как то так:
```

	@Override
	public void load(List<Film> films) {
		String inSql = String.join(",", Collections.nCopies(films.size(), "?"));
		final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));
		final String sqlQuery = "select * from GENRES g, FILM_GENRES fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";
		jdbcTemplate.query(sqlQuery, (rs) -> {
			final Film film = filmById.get(rs.getLong("FILM_ID"));
			film.addGenre(makeGenre(rs, 0));
		}, films.stream().map(StorageData::getId).toArray());
	}

	static Genre makeGenre(ResultSet rs, int rowNum) throws SQLException {
		return new Genre(
				rs.getLong("genre_id"),
				rs.getString("name"));
	}
```
И тогда в одном запросе заполняться все фильмы

2024-08-13 07:17 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                .peek(f -> f.setGenres(genreService.getGenresByFilmId(f.getId())))
В итоге будет выглядеть как то так:
	@Override
	public List<Film> getFilms() {
		final List<Film> films = filmStorage. findAll();
		genreStorage.load(films);
		return films;
	}

2024-08-13 18:51 UTC, akuniutka commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                .peek(f -> f.setGenres(genreService.getGenresByFilmId(f.getId())))
Огромное спасибо за подсказку! Меня очень смущало, что здесь столько запросов к оазе данных, и вот оно решение!

2024-08-14 14:54 UTC, YazykovMikhail approved these changes

2024-08-15 12:04 UTC, YazykovMikhail approved these changes

2024-08-16 18:50 UTC, merged